package GUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Oscar
 */
public class VentanaP extends javax.swing.JFrame {

    /**
     * Creates new form VentanaP
     */
    public VentanaP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuEmpresa = new javax.swing.JMenu();
        jMenuItemAbrirE = new javax.swing.JMenuItem();
        jMenuItemNuevaE = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuGestion = new javax.swing.JMenu();
        jMenuItemArticulos = new javax.swing.JMenuItem();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemContactos = new javax.swing.JMenuItem();
        jMenuItemProv = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemTarifas = new javax.swing.JMenuItem();
        jMenuAlmacen = new javax.swing.JMenu();
        jMenuVentas = new javax.swing.JMenu();
        jMenuItemPresuV = new javax.swing.JMenuItem();
        jMenuItemFactuV = new javax.swing.JMenuItem();
        jMenuItemAlbarV = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPedV = new javax.swing.JMenuItem();
        jMenuCompras = new javax.swing.JMenu();
        jMenuItemPedC = new javax.swing.JMenuItem();
        jMenuItemGPedC = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAlbarC = new javax.swing.JMenuItem();
        jMenuItemFactuC = new javax.swing.JMenuItem();
        jMenuTraza = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jMenuEmpresa.setBackground(new java.awt.Color(0, 0, 0));
        jMenuEmpresa.setBorder(null);
        jMenuEmpresa.setForeground(new java.awt.Color(255, 102, 0));
        jMenuEmpresa.setText("Empresa");

        jMenuItemAbrirE.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemAbrirE.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemAbrirE.setText("Abrir Empresa");
        jMenuItemAbrirE.setBorderPainted(true);
        jMenuEmpresa.add(jMenuItemAbrirE);

        jMenuItemNuevaE.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemNuevaE.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemNuevaE.setText("Nueva Empresa");
        jMenuItemNuevaE.setOpaque(true);
        jMenuEmpresa.add(jMenuItemNuevaE);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOpaque(true);
        jMenuEmpresa.add(jSeparator1);

        jMenuItemSalir.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemSalir.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.setContentAreaFilled(false);
        jMenuItemSalir.setOpaque(true);
        jMenuEmpresa.add(jMenuItemSalir);

        jMenuBar1.add(jMenuEmpresa);

        jMenuGestion.setBackground(new java.awt.Color(0, 0, 0));
        jMenuGestion.setBorder(null);
        jMenuGestion.setForeground(new java.awt.Color(255, 102, 0));
        jMenuGestion.setText("Gestión");

        jMenuItemArticulos.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemArticulos.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemArticulos.setText("Articulos");
        jMenuGestion.add(jMenuItemArticulos);

        jMenuItemClientes.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemClientes.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemClientes.setText("Clientes");
        jMenuGestion.add(jMenuItemClientes);

        jMenuItemContactos.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemContactos.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemContactos.setText("Contactos");
        jMenuGestion.add(jMenuItemContactos);

        jMenuItemProv.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemProv.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemProv.setText("Proveedores");
        jMenuGestion.add(jMenuItemProv);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOpaque(true);
        jMenuGestion.add(jSeparator2);

        jMenuItemTarifas.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemTarifas.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemTarifas.setText("Tarifas");
        jMenuGestion.add(jMenuItemTarifas);

        jMenuBar1.add(jMenuGestion);

        jMenuAlmacen.setBackground(new java.awt.Color(0, 0, 0));
        jMenuAlmacen.setBorder(null);
        jMenuAlmacen.setForeground(new java.awt.Color(255, 102, 0));
        jMenuAlmacen.setText("Almacén");
        jMenuBar1.add(jMenuAlmacen);

        jMenuVentas.setBackground(new java.awt.Color(0, 0, 0));
        jMenuVentas.setBorder(null);
        jMenuVentas.setForeground(new java.awt.Color(255, 102, 0));
        jMenuVentas.setText("Ventas");

        jMenuItemPresuV.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemPresuV.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemPresuV.setText("Presupuestos");
        jMenuItemPresuV.setOpaque(true);
        jMenuVentas.add(jMenuItemPresuV);

        jMenuItemFactuV.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemFactuV.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemFactuV.setText("Facturas");
        jMenuItemFactuV.setOpaque(true);
        jMenuVentas.add(jMenuItemFactuV);

        jMenuItemAlbarV.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemAlbarV.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemAlbarV.setText("Albaranes");
        jMenuItemAlbarV.setOpaque(true);
        jMenuVentas.add(jMenuItemAlbarV);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOpaque(true);
        jMenuVentas.add(jSeparator4);

        jMenuItemPedV.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemPedV.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemPedV.setText("Pedidos");
        jMenuItemPedV.setOpaque(true);
        jMenuVentas.add(jMenuItemPedV);

        jMenuBar1.add(jMenuVentas);

        jMenuCompras.setBackground(new java.awt.Color(0, 0, 0));
        jMenuCompras.setBorder(null);
        jMenuCompras.setForeground(new java.awt.Color(255, 102, 0));
        jMenuCompras.setText("Compras");

        jMenuItemPedC.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemPedC.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemPedC.setText("Pedidos");
        jMenuItemPedC.setBorderPainted(true);
        jMenuItemPedC.setContentAreaFilled(false);
        jMenuItemPedC.setOpaque(true);
        jMenuCompras.add(jMenuItemPedC);

        jMenuItemGPedC.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemGPedC.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemGPedC.setText("Generar Pedidos");
        jMenuItemGPedC.setOpaque(true);
        jMenuCompras.add(jMenuItemGPedC);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOpaque(true);
        jMenuCompras.add(jSeparator3);

        jMenuItemAlbarC.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemAlbarC.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemAlbarC.setText("Albaranes");
        jMenuItemAlbarC.setOpaque(true);
        jMenuCompras.add(jMenuItemAlbarC);

        jMenuItemFactuC.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemFactuC.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemFactuC.setText("Facturas");
        jMenuItemFactuC.setOpaque(true);
        jMenuCompras.add(jMenuItemFactuC);

        jMenuBar1.add(jMenuCompras);

        jMenuTraza.setBackground(new java.awt.Color(0, 0, 0));
        jMenuTraza.setBorder(null);
        jMenuTraza.setForeground(new java.awt.Color(255, 102, 0));
        jMenuTraza.setText("Trazabilidad");
        jMenuBar1.add(jMenuTraza);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1304, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAlmacen;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCompras;
    private javax.swing.JMenu jMenuEmpresa;
    private javax.swing.JMenu jMenuGestion;
    private javax.swing.JMenuItem jMenuItemAbrirE;
    private javax.swing.JMenuItem jMenuItemAlbarC;
    private javax.swing.JMenuItem jMenuItemAlbarV;
    private javax.swing.JMenuItem jMenuItemArticulos;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemContactos;
    private javax.swing.JMenuItem jMenuItemFactuC;
    private javax.swing.JMenuItem jMenuItemFactuV;
    private javax.swing.JMenuItem jMenuItemGPedC;
    private javax.swing.JMenuItem jMenuItemNuevaE;
    private javax.swing.JMenuItem jMenuItemPedC;
    private javax.swing.JMenuItem jMenuItemPedV;
    private javax.swing.JMenuItem jMenuItemPresuV;
    private javax.swing.JMenuItem jMenuItemProv;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemTarifas;
    private javax.swing.JMenu jMenuTraza;
    private javax.swing.JMenu jMenuVentas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
