package vistas;

import java.sql.Connection;
import conexiones.DBConnection;
import java.awt.CardLayout;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Oscar
 */
public class VentanaP extends javax.swing.JFrame {

    /**
     * Creates new form VentanaP
     */
    public VentanaP() {
        initComponents();
        Connection con = DBConnection.getConnection();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanelArticulos = new javax.swing.JPanel();
        jTabbedPaneArt = new javax.swing.JTabbedPane();
        jPanelLista = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelAñadir = new javax.swing.JPanel();
        jPanelGeneral = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelVentas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelCompras = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelStocks = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelDescripcion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelClientes = new javax.swing.JPanel();
        jTabbedPaneCli = new javax.swing.JTabbedPane();
        jPanelListaCli = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelAñadirCli = new javax.swing.JPanel();
        jPanelGeneralCli = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelVentasCli = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelComprasCli = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanelStocksCli = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanelDescripcionCli = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanelProv = new javax.swing.JPanel();
        jTabbedPaneProv = new javax.swing.JTabbedPane();
        jPanelListaProv = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanelAñadirProv = new javax.swing.JPanel();
        jPanelGeneralProv = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanelVentasProv = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanelComprasProv = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanelStocksProv = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanelDescripcionProv = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuEmpresa = new javax.swing.JMenu();
        jMenuItemAbrirE = new javax.swing.JMenuItem();
        jMenuItemNuevaE = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuGestion = new javax.swing.JMenu();
        jMenuItemArticulos = new javax.swing.JMenuItem();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemContactos = new javax.swing.JMenuItem();
        jMenuItemProv = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemTarifas = new javax.swing.JMenuItem();
        jMenuAlmacen = new javax.swing.JMenu();
        jMenuVentas = new javax.swing.JMenu();
        jMenuItemPresuV = new javax.swing.JMenuItem();
        jMenuItemFactuV = new javax.swing.JMenuItem();
        jMenuItemAlbarV = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPedV = new javax.swing.JMenuItem();
        jMenuCompras = new javax.swing.JMenu();
        jMenuItemPedC = new javax.swing.JMenuItem();
        jMenuItemGPedC = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAlbarC = new javax.swing.JMenuItem();
        jMenuItemFactuC = new javax.swing.JMenuItem();
        jMenuTraza = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1299, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        jPanelPrincipal.add(jPanel1, "card5");

        jPanelArticulos.setBackground(new java.awt.Color(255, 243, 218));

        jTabbedPaneArt.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("SketchFlow Print", 3, 36)); // NOI18N
        jLabel1.setText("Lista");

        javax.swing.GroupLayout jPanelListaLayout = new javax.swing.GroupLayout(jPanelLista);
        jPanelLista.setLayout(jPanelListaLayout);
        jPanelListaLayout.setHorizontalGroup(
            jPanelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1164, Short.MAX_VALUE))
        );
        jPanelListaLayout.setVerticalGroup(
            jPanelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPaneArt.addTab("Lista", jPanelLista);

        javax.swing.GroupLayout jPanelAñadirLayout = new javax.swing.GroupLayout(jPanelAñadir);
        jPanelAñadir.setLayout(jPanelAñadirLayout);
        jPanelAñadirLayout.setHorizontalGroup(
            jPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1294, Short.MAX_VALUE)
        );
        jPanelAñadirLayout.setVerticalGroup(
            jPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jTabbedPaneArt.addTab("Añadir", jPanelAñadir);

        jLabel2.setFont(new java.awt.Font("SketchFlow Print", 3, 36)); // NOI18N
        jLabel2.setText("General");

        javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1107, Short.MAX_VALUE))
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPaneArt.addTab("General", jPanelGeneral);

        jLabel3.setFont(new java.awt.Font("SketchFlow Print", 3, 36)); // NOI18N
        jLabel3.setText("Ventas");

        javax.swing.GroupLayout jPanelVentasLayout = new javax.swing.GroupLayout(jPanelVentas);
        jPanelVentas.setLayout(jPanelVentasLayout);
        jPanelVentasLayout.setHorizontalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1133, Short.MAX_VALUE))
        );
        jPanelVentasLayout.setVerticalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPaneArt.addTab("Ventas", jPanelVentas);

        jLabel4.setFont(new java.awt.Font("SketchFlow Print", 3, 36)); // NOI18N
        jLabel4.setText("Compras");

        javax.swing.GroupLayout jPanelComprasLayout = new javax.swing.GroupLayout(jPanelCompras);
        jPanelCompras.setLayout(jPanelComprasLayout);
        jPanelComprasLayout.setHorizontalGroup(
            jPanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComprasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1078, Short.MAX_VALUE))
        );
        jPanelComprasLayout.setVerticalGroup(
            jPanelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComprasLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPaneArt.addTab("Compras", jPanelCompras);

        jLabel5.setFont(new java.awt.Font("SketchFlow Print", 3, 36)); // NOI18N
        jLabel5.setText("Stocks");

        javax.swing.GroupLayout jPanelStocksLayout = new javax.swing.GroupLayout(jPanelStocks);
        jPanelStocks.setLayout(jPanelStocksLayout);
        jPanelStocksLayout.setHorizontalGroup(
            jPanelStocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStocksLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1130, Short.MAX_VALUE))
        );
        jPanelStocksLayout.setVerticalGroup(
            jPanelStocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStocksLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPaneArt.addTab("Stocks", jPanelStocks);

        javax.swing.GroupLayout jPanelDescripcionLayout = new javax.swing.GroupLayout(jPanelDescripcion);
        jPanelDescripcion.setLayout(jPanelDescripcionLayout);
        jPanelDescripcionLayout.setHorizontalGroup(
            jPanelDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1294, Short.MAX_VALUE)
        );
        jPanelDescripcionLayout.setVerticalGroup(
            jPanelDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jTabbedPaneArt.addTab("Descripción", jPanelDescripcion);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 102));
        jLabel6.setText("Articulos");

        javax.swing.GroupLayout jPanelArticulosLayout = new javax.swing.GroupLayout(jPanelArticulos);
        jPanelArticulos.setLayout(jPanelArticulosLayout);
        jPanelArticulosLayout.setHorizontalGroup(
            jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneArt)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelArticulosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(625, 625, 625))
        );
        jPanelArticulosLayout.setVerticalGroup(
            jPanelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelArticulosLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneArt))
        );

        jPanelPrincipal.add(jPanelArticulos, "card2");

        jPanelClientes.setBackground(new java.awt.Color(255, 243, 218));

        jTabbedPaneCli.setAutoscrolls(true);

        jLabel7.setFont(new java.awt.Font("SketchFlow Print", 3, 36)); // NOI18N
        jLabel7.setText("Lista");

        javax.swing.GroupLayout jPanelListaCliLayout = new javax.swing.GroupLayout(jPanelListaCli);
        jPanelListaCli.setLayout(jPanelListaCliLayout);
        jPanelListaCliLayout.setHorizontalGroup(
            jPanelListaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaCliLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1164, Short.MAX_VALUE))
        );
        jPanelListaCliLayout.setVerticalGroup(
            jPanelListaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaCliLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPaneCli.addTab("Lista", jPanelListaCli);

        javax.swing.GroupLayout jPanelAñadirCliLayout = new javax.swing.GroupLayout(jPanelAñadirCli);
        jPanelAñadirCli.setLayout(jPanelAñadirCliLayout);
        jPanelAñadirCliLayout.setHorizontalGroup(
            jPanelAñadirCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1294, Short.MAX_VALUE)
        );
        jPanelAñadirCliLayout.setVerticalGroup(
            jPanelAñadirCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jTabbedPaneCli.addTab("Añadir", jPanelAñadirCli);

        jLabel8.setFont(new java.awt.Font("SketchFlow Print", 3, 36)); // NOI18N
        jLabel8.setText("General");

        javax.swing.GroupLayout jPanelGeneralCliLayout = new javax.swing.GroupLayout(jPanelGeneralCli);
        jPanelGeneralCli.setLayout(jPanelGeneralCliLayout);
        jPanelGeneralCliLayout.setHorizontalGroup(
            jPanelGeneralCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralCliLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1107, Short.MAX_VALUE))
        );
        jPanelGeneralCliLayout.setVerticalGroup(
            jPanelGeneralCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralCliLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPaneCli.addTab("General", jPanelGeneralCli);

        jLabel9.setFont(new java.awt.Font("SketchFlow Print", 3, 36)); // NOI18N
        jLabel9.setText("Ventas");

        javax.swing.GroupLayout jPanelVentasCliLayout = new javax.swing.GroupLayout(jPanelVentasCli);
        jPanelVentasCli.setLayout(jPanelVentasCliLayout);
        jPanelVentasCliLayout.setHorizontalGroup(
            jPanelVentasCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasCliLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1133, Short.MAX_VALUE))
        );
        jPanelVentasCliLayout.setVerticalGroup(
            jPanelVentasCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasCliLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPaneCli.addTab("Ventas", jPanelVentasCli);

        jLabel10.setFont(new java.awt.Font("SketchFlow Print", 3, 36)); // NOI18N
        jLabel10.setText("Compras");

        javax.swing.GroupLayout jPanelComprasCliLayout = new javax.swing.GroupLayout(jPanelComprasCli);
        jPanelComprasCli.setLayout(jPanelComprasCliLayout);
        jPanelComprasCliLayout.setHorizontalGroup(
            jPanelComprasCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComprasCliLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1078, Short.MAX_VALUE))
        );
        jPanelComprasCliLayout.setVerticalGroup(
            jPanelComprasCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComprasCliLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPaneCli.addTab("Compras", jPanelComprasCli);

        jLabel11.setFont(new java.awt.Font("SketchFlow Print", 3, 36)); // NOI18N
        jLabel11.setText("Stocks");

        javax.swing.GroupLayout jPanelStocksCliLayout = new javax.swing.GroupLayout(jPanelStocksCli);
        jPanelStocksCli.setLayout(jPanelStocksCliLayout);
        jPanelStocksCliLayout.setHorizontalGroup(
            jPanelStocksCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStocksCliLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1130, Short.MAX_VALUE))
        );
        jPanelStocksCliLayout.setVerticalGroup(
            jPanelStocksCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStocksCliLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPaneCli.addTab("Stocks", jPanelStocksCli);

        javax.swing.GroupLayout jPanelDescripcionCliLayout = new javax.swing.GroupLayout(jPanelDescripcionCli);
        jPanelDescripcionCli.setLayout(jPanelDescripcionCliLayout);
        jPanelDescripcionCliLayout.setHorizontalGroup(
            jPanelDescripcionCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1294, Short.MAX_VALUE)
        );
        jPanelDescripcionCliLayout.setVerticalGroup(
            jPanelDescripcionCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jTabbedPaneCli.addTab("Descripción", jPanelDescripcionCli);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 102));
        jLabel12.setText("Clientes");

        javax.swing.GroupLayout jPanelClientesLayout = new javax.swing.GroupLayout(jPanelClientes);
        jPanelClientes.setLayout(jPanelClientesLayout);
        jPanelClientesLayout.setHorizontalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneCli)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(640, 640, 640))
        );
        jPanelClientesLayout.setVerticalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClientesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneCli))
        );

        jPanelPrincipal.add(jPanelClientes, "card2");

        jPanelProv.setBackground(new java.awt.Color(255, 243, 218));

        jTabbedPaneProv.setAutoscrolls(true);

        jLabel13.setFont(new java.awt.Font("SketchFlow Print", 3, 36)); // NOI18N
        jLabel13.setText("Lista");

        javax.swing.GroupLayout jPanelListaProvLayout = new javax.swing.GroupLayout(jPanelListaProv);
        jPanelListaProv.setLayout(jPanelListaProvLayout);
        jPanelListaProvLayout.setHorizontalGroup(
            jPanelListaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaProvLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1164, Short.MAX_VALUE))
        );
        jPanelListaProvLayout.setVerticalGroup(
            jPanelListaProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaProvLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel13)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPaneProv.addTab("Lista", jPanelListaProv);

        javax.swing.GroupLayout jPanelAñadirProvLayout = new javax.swing.GroupLayout(jPanelAñadirProv);
        jPanelAñadirProv.setLayout(jPanelAñadirProvLayout);
        jPanelAñadirProvLayout.setHorizontalGroup(
            jPanelAñadirProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1294, Short.MAX_VALUE)
        );
        jPanelAñadirProvLayout.setVerticalGroup(
            jPanelAñadirProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jTabbedPaneProv.addTab("Añadir", jPanelAñadirProv);

        jLabel14.setFont(new java.awt.Font("SketchFlow Print", 3, 36)); // NOI18N
        jLabel14.setText("General");

        javax.swing.GroupLayout jPanelGeneralProvLayout = new javax.swing.GroupLayout(jPanelGeneralProv);
        jPanelGeneralProv.setLayout(jPanelGeneralProvLayout);
        jPanelGeneralProvLayout.setHorizontalGroup(
            jPanelGeneralProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralProvLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1107, Short.MAX_VALUE))
        );
        jPanelGeneralProvLayout.setVerticalGroup(
            jPanelGeneralProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralProvLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel14)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPaneProv.addTab("General", jPanelGeneralProv);

        jLabel15.setFont(new java.awt.Font("SketchFlow Print", 3, 36)); // NOI18N
        jLabel15.setText("Ventas");

        javax.swing.GroupLayout jPanelVentasProvLayout = new javax.swing.GroupLayout(jPanelVentasProv);
        jPanelVentasProv.setLayout(jPanelVentasProvLayout);
        jPanelVentasProvLayout.setHorizontalGroup(
            jPanelVentasProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasProvLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1133, Short.MAX_VALUE))
        );
        jPanelVentasProvLayout.setVerticalGroup(
            jPanelVentasProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasProvLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel15)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPaneProv.addTab("Ventas", jPanelVentasProv);

        jLabel16.setFont(new java.awt.Font("SketchFlow Print", 3, 36)); // NOI18N
        jLabel16.setText("Compras");

        javax.swing.GroupLayout jPanelComprasProvLayout = new javax.swing.GroupLayout(jPanelComprasProv);
        jPanelComprasProv.setLayout(jPanelComprasProvLayout);
        jPanelComprasProvLayout.setHorizontalGroup(
            jPanelComprasProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComprasProvLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1078, Short.MAX_VALUE))
        );
        jPanelComprasProvLayout.setVerticalGroup(
            jPanelComprasProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComprasProvLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel16)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPaneProv.addTab("Compras", jPanelComprasProv);

        jLabel17.setFont(new java.awt.Font("SketchFlow Print", 3, 36)); // NOI18N
        jLabel17.setText("Stocks");

        javax.swing.GroupLayout jPanelStocksProvLayout = new javax.swing.GroupLayout(jPanelStocksProv);
        jPanelStocksProv.setLayout(jPanelStocksProvLayout);
        jPanelStocksProvLayout.setHorizontalGroup(
            jPanelStocksProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStocksProvLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1130, Short.MAX_VALUE))
        );
        jPanelStocksProvLayout.setVerticalGroup(
            jPanelStocksProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStocksProvLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel17)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jTabbedPaneProv.addTab("Stocks", jPanelStocksProv);

        javax.swing.GroupLayout jPanelDescripcionProvLayout = new javax.swing.GroupLayout(jPanelDescripcionProv);
        jPanelDescripcionProv.setLayout(jPanelDescripcionProvLayout);
        jPanelDescripcionProvLayout.setHorizontalGroup(
            jPanelDescripcionProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1294, Short.MAX_VALUE)
        );
        jPanelDescripcionProvLayout.setVerticalGroup(
            jPanelDescripcionProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jTabbedPaneProv.addTab("Descripción", jPanelDescripcionProv);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 153, 102));
        jLabel18.setText("Proveedores");

        javax.swing.GroupLayout jPanelProvLayout = new javax.swing.GroupLayout(jPanelProv);
        jPanelProv.setLayout(jPanelProvLayout);
        jPanelProvLayout.setHorizontalGroup(
            jPanelProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneProv)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProvLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(630, 630, 630))
        );
        jPanelProvLayout.setVerticalGroup(
            jPanelProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProvLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneProv))
        );

        jPanelPrincipal.add(jPanelProv, "card2");

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jMenuEmpresa.setBackground(new java.awt.Color(0, 0, 0));
        jMenuEmpresa.setBorder(null);
        jMenuEmpresa.setForeground(new java.awt.Color(255, 102, 0));
        jMenuEmpresa.setText("Empresa");

        jMenuItemAbrirE.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemAbrirE.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemAbrirE.setText("Abrir Empresa");
        jMenuItemAbrirE.setBorderPainted(true);
        jMenuEmpresa.add(jMenuItemAbrirE);

        jMenuItemNuevaE.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemNuevaE.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemNuevaE.setText("Nueva Empresa");
        jMenuItemNuevaE.setOpaque(true);
        jMenuEmpresa.add(jMenuItemNuevaE);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOpaque(true);
        jMenuEmpresa.add(jSeparator1);

        jMenuItemSalir.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemSalir.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.setContentAreaFilled(false);
        jMenuItemSalir.setOpaque(true);
        jMenuEmpresa.add(jMenuItemSalir);

        jMenuBar1.add(jMenuEmpresa);

        jMenuGestion.setBackground(new java.awt.Color(0, 0, 0));
        jMenuGestion.setBorder(null);
        jMenuGestion.setForeground(new java.awt.Color(255, 102, 0));
        jMenuGestion.setText("Gestión");

        jMenuItemArticulos.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemArticulos.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemArticulos.setText("Articulos");
        jMenuItemArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemArticulosActionPerformed(evt);
            }
        });
        jMenuGestion.add(jMenuItemArticulos);

        jMenuItemClientes.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemClientes.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemClientes.setText("Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenuGestion.add(jMenuItemClientes);

        jMenuItemContactos.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemContactos.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemContactos.setText("Contactos");
        jMenuGestion.add(jMenuItemContactos);

        jMenuItemProv.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemProv.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemProv.setText("Proveedores");
        jMenuItemProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProvActionPerformed(evt);
            }
        });
        jMenuGestion.add(jMenuItemProv);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOpaque(true);
        jMenuGestion.add(jSeparator2);

        jMenuItemTarifas.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemTarifas.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemTarifas.setText("Tarifas");
        jMenuGestion.add(jMenuItemTarifas);

        jMenuBar1.add(jMenuGestion);

        jMenuAlmacen.setBackground(new java.awt.Color(0, 0, 0));
        jMenuAlmacen.setBorder(null);
        jMenuAlmacen.setForeground(new java.awt.Color(255, 102, 0));
        jMenuAlmacen.setText("Almacén");
        jMenuBar1.add(jMenuAlmacen);

        jMenuVentas.setBackground(new java.awt.Color(0, 0, 0));
        jMenuVentas.setBorder(null);
        jMenuVentas.setForeground(new java.awt.Color(255, 102, 0));
        jMenuVentas.setText("Ventas");

        jMenuItemPresuV.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemPresuV.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemPresuV.setText("Presupuestos");
        jMenuItemPresuV.setOpaque(true);
        jMenuVentas.add(jMenuItemPresuV);

        jMenuItemFactuV.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemFactuV.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemFactuV.setText("Facturas");
        jMenuItemFactuV.setOpaque(true);
        jMenuVentas.add(jMenuItemFactuV);

        jMenuItemAlbarV.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemAlbarV.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemAlbarV.setText("Albaranes");
        jMenuItemAlbarV.setOpaque(true);
        jMenuVentas.add(jMenuItemAlbarV);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOpaque(true);
        jMenuVentas.add(jSeparator4);

        jMenuItemPedV.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemPedV.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemPedV.setText("Pedidos");
        jMenuItemPedV.setOpaque(true);
        jMenuVentas.add(jMenuItemPedV);

        jMenuBar1.add(jMenuVentas);

        jMenuCompras.setBackground(new java.awt.Color(0, 0, 0));
        jMenuCompras.setBorder(null);
        jMenuCompras.setForeground(new java.awt.Color(255, 102, 0));
        jMenuCompras.setText("Compras");

        jMenuItemPedC.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemPedC.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemPedC.setText("Pedidos");
        jMenuItemPedC.setBorderPainted(true);
        jMenuItemPedC.setContentAreaFilled(false);
        jMenuItemPedC.setOpaque(true);
        jMenuCompras.add(jMenuItemPedC);

        jMenuItemGPedC.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemGPedC.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemGPedC.setText("Generar Pedidos");
        jMenuItemGPedC.setOpaque(true);
        jMenuCompras.add(jMenuItemGPedC);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOpaque(true);
        jMenuCompras.add(jSeparator3);

        jMenuItemAlbarC.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemAlbarC.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemAlbarC.setText("Albaranes");
        jMenuItemAlbarC.setOpaque(true);
        jMenuCompras.add(jMenuItemAlbarC);

        jMenuItemFactuC.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemFactuC.setForeground(new java.awt.Color(204, 204, 0));
        jMenuItemFactuC.setText("Facturas");
        jMenuItemFactuC.setOpaque(true);
        jMenuCompras.add(jMenuItemFactuC);

        jMenuBar1.add(jMenuCompras);

        jMenuTraza.setBackground(new java.awt.Color(0, 0, 0));
        jMenuTraza.setBorder(null);
        jMenuTraza.setForeground(new java.awt.Color(255, 102, 0));
        jMenuTraza.setText("Trazabilidad");
        jMenuBar1.add(jMenuTraza);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1299, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemArticulosActionPerformed
        cambiarCard(jPanelArticulos);
        
    }//GEN-LAST:event_jMenuItemArticulosActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
        cambiarCard(jPanelClientes);
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void jMenuItemProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProvActionPerformed
       cambiarCard(jPanelProv);
    }//GEN-LAST:event_jMenuItemProvActionPerformed

    private void cambiarCard(JPanel panel ){
        jPanelPrincipal.removeAll();
        jPanelPrincipal.add(panel);
        jPanelPrincipal.repaint();
        jPanelPrincipal.revalidate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenuAlmacen;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCompras;
    private javax.swing.JMenu jMenuEmpresa;
    private javax.swing.JMenu jMenuGestion;
    private javax.swing.JMenuItem jMenuItemAbrirE;
    private javax.swing.JMenuItem jMenuItemAlbarC;
    private javax.swing.JMenuItem jMenuItemAlbarV;
    private javax.swing.JMenuItem jMenuItemArticulos;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemContactos;
    private javax.swing.JMenuItem jMenuItemFactuC;
    private javax.swing.JMenuItem jMenuItemFactuV;
    private javax.swing.JMenuItem jMenuItemGPedC;
    private javax.swing.JMenuItem jMenuItemNuevaE;
    private javax.swing.JMenuItem jMenuItemPedC;
    private javax.swing.JMenuItem jMenuItemPedV;
    private javax.swing.JMenuItem jMenuItemPresuV;
    private javax.swing.JMenuItem jMenuItemProv;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemTarifas;
    private javax.swing.JMenu jMenuTraza;
    private javax.swing.JMenu jMenuVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelArticulos;
    private javax.swing.JPanel jPanelAñadir;
    private javax.swing.JPanel jPanelAñadirCli;
    private javax.swing.JPanel jPanelAñadirProv;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JPanel jPanelCompras;
    private javax.swing.JPanel jPanelComprasCli;
    private javax.swing.JPanel jPanelComprasProv;
    private javax.swing.JPanel jPanelDescripcion;
    private javax.swing.JPanel jPanelDescripcionCli;
    private javax.swing.JPanel jPanelDescripcionProv;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JPanel jPanelGeneralCli;
    private javax.swing.JPanel jPanelGeneralProv;
    private javax.swing.JPanel jPanelLista;
    private javax.swing.JPanel jPanelListaCli;
    private javax.swing.JPanel jPanelListaProv;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelProv;
    private javax.swing.JPanel jPanelStocks;
    private javax.swing.JPanel jPanelStocksCli;
    private javax.swing.JPanel jPanelStocksProv;
    private javax.swing.JPanel jPanelVentas;
    private javax.swing.JPanel jPanelVentasCli;
    private javax.swing.JPanel jPanelVentasProv;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPaneArt;
    private javax.swing.JTabbedPane jTabbedPaneCli;
    private javax.swing.JTabbedPane jTabbedPaneProv;
    // End of variables declaration//GEN-END:variables
}
