package modelos;
// Generated 14-abr-2015 21:45:23 by Hibernate Tools 4.3.1



/**
 * Albaran generated by hbm2java
 */
public class Albaran  implements java.io.Serializable {


     private Integer numero;

    public Albaran() {
    }

   
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }




}


