package modelos;
// Generated 11-abr-2015 20:27:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private Integer idArticulo;
    // private Estados estados;
     private int estado;
     private String nombre;
     private Float peso;
     private String tipo;
     private float precio;
     private float iva;
     private String descripcion;
     private String origen;
     private String destino;
     private Set lineaPedidoPs = new HashSet(0);
     private Set lineaPedidoCs = new HashSet(0);

    public Articulo() {
    }

	
    public Articulo(int estado, String nombre, String tipo, float precio, float iva, String origen, String destino) {
        this.estado = estado;
        this.nombre = nombre;
        this.tipo = tipo;
        this.precio = precio;
        this.iva = iva;
        this.origen = origen;
        this.destino = destino;
    }
    public Articulo(int estado, String nombre, Float peso, String tipo, float precio, float iva, String descripcion, String origen, String destino) {
       this.estado = estado;
       this.nombre = nombre;
       this.peso = peso;
       this.tipo = tipo;
       this.precio = precio;
       this.iva = iva;
       this.descripcion = descripcion;
       this.origen = origen;
       this.destino = destino;
    }
   
    public Integer getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(Integer idArticulo) {
        this.idArticulo = idArticulo;
    }
    public int getEstados() {
        return this.estado;
    }
    
    public void setEstados(int estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Float getPeso() {
        return this.peso;
    }
    
    public void setPeso(Float peso) {
        this.peso = peso;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public float getIva() {
        return this.iva;
    }
    
    public void setIva(float iva) {
        this.iva = iva;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }
    public Set getLineaPedidoPs() {
        return this.lineaPedidoPs;
    }
    
    public void setLineaPedidoPs(Set lineaPedidoPs) {
        this.lineaPedidoPs = lineaPedidoPs;
    }
    public Set getLineaPedidoCs() {
        return this.lineaPedidoCs;
    }
    
    public void setLineaPedidoCs(Set lineaPedidoCs) {
        this.lineaPedidoCs = lineaPedidoCs;
    }




}


