package modelos;
// Generated 14-abr-2015 21:45:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private String idArt;
     private int estado;
     private String nombre;
     private Float peso;
     private String tipo;
     private float precio;
     private float iva;
     private String descripcion;
     private String origen;
     private String imagen;
     private Set lineaPedidoPs = new HashSet(0);
     private Set lineaPedidoCs = new HashSet(0);

    public Articulo() {
    }

	
    public Articulo(String idArt, int estado, String nombre, String tipo, float precio, float iva, String origen) {
        this.idArt = idArt;
        this.estado = estado;
        this.nombre = nombre;
        this.tipo = tipo;
        this.precio = precio;
        this.iva = iva;
        this.origen = origen;
    }
    public Articulo(String idArt, int estado, String nombre, Float peso, String tipo, float precio, float iva, String descripcion, String origen) {
       this.idArt = idArt;
       this.estado = estado;
       this.nombre = nombre;
       this.peso = peso;
       this.tipo = tipo;
       this.precio = precio;
       this.iva = iva;
       this.descripcion = descripcion;
       this.origen = origen;
    }
   
    public String getIdArt() {
        return this.idArt;
    }
    
    public void setIdArt(String idArt) {
        this.idArt = idArt;
    }
    public int getEstados() {
        return this.estado;
    }
    
    public void setEstados(int estados) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Float getPeso() {
        return this.peso;
    }
    
    public void setPeso(Float peso) {
        this.peso = peso;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public float getIva() {
        return this.iva;
    }
    
    public void setIva(float iva) {
        this.iva = iva;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
   
}


