package modelos;
// Generated 14-abr-2015 21:45:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoPed generated by hbm2java
 */
public class EstadoPed  implements java.io.Serializable {


     private Integer idEstados;
     private String nombreE;
     private Set pedidoPs = new HashSet(0);
     private Set pedidoCs = new HashSet(0);

    public EstadoPed() {
    }

	
    public EstadoPed(String nombreE) {
        this.nombreE = nombreE;
    }
    public EstadoPed(String nombreE, Set pedidoPs, Set pedidoCs) {
       this.nombreE = nombreE;
       this.pedidoPs = pedidoPs;
       this.pedidoCs = pedidoCs;
    }
   
    public Integer getIdEstados() {
        return this.idEstados;
    }
    
    public void setIdEstados(Integer idEstados) {
        this.idEstados = idEstados;
    }
    public String getNombreE() {
        return this.nombreE;
    }
    
    public void setNombreE(String nombreE) {
        this.nombreE = nombreE;
    }
    public Set getPedidoPs() {
        return this.pedidoPs;
    }
    
    public void setPedidoPs(Set pedidoPs) {
        this.pedidoPs = pedidoPs;
    }
    public Set getPedidoCs() {
        return this.pedidoCs;
    }
    
    public void setPedidoCs(Set pedidoCs) {
        this.pedidoCs = pedidoCs;
    }




}


