package modelos;
// Generated 14-abr-2015 21:45:23 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Facturas generated by hbm2java
 */
public class Facturas  implements java.io.Serializable {


     private Integer numero;
     private int empresa;
     private int facturado;
     private int enviado;
     private Date fecha;
     private String tipoPed;
     private String formaPago;
     private int cliente;
     private Float totalBruto;
     private Float dto;
     private Float dpp;
     private Float portes;
     private Float iva;
     private Float re;
     private Float cuotaRe;
     private Float total;
     private Set lineaFacturas = new HashSet(0);

    public Facturas() {
    }

	
    public Facturas(int empresa, int facturado, int enviado, Date fecha, String tipoPed, String formaPago, int cliente) {
        this.empresa = empresa;
        this.facturado = facturado;
        this.enviado = enviado;
        this.fecha = fecha;
        this.tipoPed = tipoPed;
        this.formaPago = formaPago;
        this.cliente = cliente;
    }
    public Facturas(int empresa, int facturado, int enviado, Date fecha, String tipoPed, String formaPago, int cliente, Float totalBruto, Float dto, Float dpp, Float portes, Float iva, Float re, Float cuotaRe, Float total, Set lineaFacturas) {
       this.empresa = empresa;
       this.facturado = facturado;
       this.enviado = enviado;
       this.fecha = fecha;
       this.tipoPed = tipoPed;
       this.formaPago = formaPago;
       this.cliente = cliente;
       this.totalBruto = totalBruto;
       this.dto = dto;
       this.dpp = dpp;
       this.portes = portes;
       this.iva = iva;
       this.re = re;
       this.cuotaRe = cuotaRe;
       this.total = total;
       this.lineaFacturas = lineaFacturas;
    }
   
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public int getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(int empresa) {
        this.empresa = empresa;
    }
    public int getFacturado() {
        return this.facturado;
    }
    
    public void setFacturado(int facturado) {
        this.facturado = facturado;
    }
    public int getEnviado() {
        return this.enviado;
    }
    
    public void setEnviado(int enviado) {
        this.enviado = enviado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTipoPed() {
        return this.tipoPed;
    }
    
    public void setTipoPed(String tipoPed) {
        this.tipoPed = tipoPed;
    }
    public String getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(String formaPago) {
        this.formaPago = formaPago;
    }
    public int getCliente() {
        return this.cliente;
    }
    
    public void setCliente(int cliente) {
        this.cliente = cliente;
    }
    public Float getTotalBruto() {
        return this.totalBruto;
    }
    
    public void setTotalBruto(Float totalBruto) {
        this.totalBruto = totalBruto;
    }
    public Float getDto() {
        return this.dto;
    }
    
    public void setDto(Float dto) {
        this.dto = dto;
    }
    public Float getDpp() {
        return this.dpp;
    }
    
    public void setDpp(Float dpp) {
        this.dpp = dpp;
    }
    public Float getPortes() {
        return this.portes;
    }
    
    public void setPortes(Float portes) {
        this.portes = portes;
    }
    public Float getIva() {
        return this.iva;
    }
    
    public void setIva(Float iva) {
        this.iva = iva;
    }
    public Float getRe() {
        return this.re;
    }
    
    public void setRe(Float re) {
        this.re = re;
    }
    public Float getCuotaRe() {
        return this.cuotaRe;
    }
    
    public void setCuotaRe(Float cuotaRe) {
        this.cuotaRe = cuotaRe;
    }
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }
    public Set getLineaFacturas() {
        return this.lineaFacturas;
    }
    
    public void setLineaFacturas(Set lineaFacturas) {
        this.lineaFacturas = lineaFacturas;
    }




}


