package modelos;
// Generated 14-abr-2015 21:45:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FormaPago generated by hbm2java
 */
public class FormaPago  implements java.io.Serializable {


     private Integer idPago;
     private String tipo;
     private Set pedidoPs = new HashSet(0);
     private Set pedidoCs = new HashSet(0);

    public FormaPago() {
    }

	
    public FormaPago(String tipo) {
        this.tipo = tipo;
    }
    public FormaPago(String tipo, Set pedidoPs, Set pedidoCs) {
       this.tipo = tipo;
       this.pedidoPs = pedidoPs;
       this.pedidoCs = pedidoCs;
    }
   
    public Integer getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(Integer idPago) {
        this.idPago = idPago;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getPedidoPs() {
        return this.pedidoPs;
    }
    
    public void setPedidoPs(Set pedidoPs) {
        this.pedidoPs = pedidoPs;
    }
    public Set getPedidoCs() {
        return this.pedidoCs;
    }
    
    public void setPedidoCs(Set pedidoCs) {
        this.pedidoCs = pedidoCs;
    }




}


