package modelos;
// Generated 14-abr-2015 0:15:55 by Hibernate Tools 4.3.1



/**
 * Iva generated by hbm2java
 */
public class Iva  implements java.io.Serializable {


     private Integer idIva;
     private float porcentaje;

    public Iva() {
    }

    public Iva(float porcentaje) {
       this.porcentaje = porcentaje;
    }
   
    public Integer getIdIva() {
        return this.idIva;
    }
    
    public void setIdIva(Integer idIva) {
        this.idIva = idIva;
    }
    public float getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(float porcentaje) {
        this.porcentaje = porcentaje;
    }




}


