package modelos;
// Generated 11-abr-2015 20:27:45 by Hibernate Tools 4.3.1



/**
 * LineaPedidoC generated by hbm2java
 */
public class LineaPedidoC  implements java.io.Serializable {


     private String linea;
     private Articulo articulo;
     private PedidoC pedidoC;
     private int cantidad;

    public LineaPedidoC() {
    }

    public LineaPedidoC(String linea, Articulo articulo, PedidoC pedidoC, int cantidad) {
       this.linea = linea;
       this.articulo = articulo;
       this.pedidoC = pedidoC;
       this.cantidad = cantidad;
    }
   
    public String getLinea() {
        return this.linea;
    }
    
    public void setLinea(String linea) {
        this.linea = linea;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public PedidoC getPedidoC() {
        return this.pedidoC;
    }
    
    public void setPedidoC(PedidoC pedidoC) {
        this.pedidoC = pedidoC;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


