package modelos;
// Generated 14-abr-2015 0:15:55 by Hibernate Tools 4.3.1



/**
 * LineaFactura generated by hbm2java
 */
public class LineaFactura  implements java.io.Serializable {


     private LineaFacturaId id;
     private Facturas facturas;
     private int articulo;
     private int cantidad;
     private float precio;
     private float iva;
     private Float importe;

    public LineaFactura() {
    }

	
    public LineaFactura(LineaFacturaId id, Facturas facturas, int articulo, int cantidad, float precio, float iva) {
        this.id = id;
        this.facturas = facturas;
        this.articulo = articulo;
        this.cantidad = cantidad;
        this.precio = precio;
        this.iva = iva;
    }
    public LineaFactura(LineaFacturaId id, Facturas facturas, int articulo, int cantidad, float precio, float iva, Float importe) {
       this.id = id;
       this.facturas = facturas;
       this.articulo = articulo;
       this.cantidad = cantidad;
       this.precio = precio;
       this.iva = iva;
       this.importe = importe;
    }
   
    public LineaFacturaId getId() {
        return this.id;
    }
    
    public void setId(LineaFacturaId id) {
        this.id = id;
    }
    public Facturas getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Facturas facturas) {
        this.facturas = facturas;
    }
    public int getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(int articulo) {
        this.articulo = articulo;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public float getIva() {
        return this.iva;
    }
    
    public void setIva(float iva) {
        this.iva = iva;
    }
    public Float getImporte() {
        return this.importe;
    }
    
    public void setImporte(Float importe) {
        this.importe = importe;
    }




}


