package modelos;
// Generated 11-abr-2015 20:27:45 by Hibernate Tools 4.3.1



/**
 * LineaPedidoPId generated by hbm2java
 */
public class LineaPedidoPId  implements java.io.Serializable {


     private int linea;
     private int articuloIdArticulo;

    public LineaPedidoPId() {
    }

    public LineaPedidoPId(int linea, int articuloIdArticulo) {
       this.linea = linea;
       this.articuloIdArticulo = articuloIdArticulo;
    }
   
    public int getLinea() {
        return this.linea;
    }
    
    public void setLinea(int linea) {
        this.linea = linea;
    }
    public int getArticuloIdArticulo() {
        return this.articuloIdArticulo;
    }
    
    public void setArticuloIdArticulo(int articuloIdArticulo) {
        this.articuloIdArticulo = articuloIdArticulo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LineaPedidoPId) ) return false;
		 LineaPedidoPId castOther = ( LineaPedidoPId ) other; 
         
		 return (this.getLinea()==castOther.getLinea())
 && (this.getArticuloIdArticulo()==castOther.getArticuloIdArticulo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLinea();
         result = 37 * result + this.getArticuloIdArticulo();
         return result;
   }   


}


