package modelos;
// Generated 14-abr-2015 21:45:23 by Hibernate Tools 4.3.1



/**
 * LineaPedidoC generated by hbm2java
 */
public class LineaPedidoC  implements java.io.Serializable {


     private LineaPedidoCId id;
     private Articulo articulo;
     private PedidoC pedidoC;
     private int cantidad;
     private Float total;

    public LineaPedidoC() {
    }

	
    public LineaPedidoC(LineaPedidoCId id, Articulo articulo, PedidoC pedidoC, int cantidad) {
        this.id = id;
        this.articulo = articulo;
        this.pedidoC = pedidoC;
        this.cantidad = cantidad;
    }
    public LineaPedidoC(LineaPedidoCId id, Articulo articulo, PedidoC pedidoC, int cantidad, Float total) {
       this.id = id;
       this.articulo = articulo;
       this.pedidoC = pedidoC;
       this.cantidad = cantidad;
       this.total = total;
    }
   
    public LineaPedidoCId getId() {
        return this.id;
    }
    
    public void setId(LineaPedidoCId id) {
        this.id = id;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public PedidoC getPedidoC() {
        return this.pedidoC;
    }
    
    public void setPedidoC(PedidoC pedidoC) {
        this.pedidoC = pedidoC;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }




}


