package modelos;
// Generated 11-abr-2015 20:27:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PedidoC generated by hbm2java
 */
public class PedidoC  implements java.io.Serializable {


     private Integer idPedidoC;
     private Cliente cliente;
     private EstadoPed estadoPed;
     private Date fechaA;
     private Float total;
     private Set lineaPedidoCs = new HashSet(0);

    public PedidoC() {
    }

	
    public PedidoC(Cliente cliente, EstadoPed estadoPed, Date fechaA) {
        this.cliente = cliente;
        this.estadoPed = estadoPed;
        this.fechaA = fechaA;
    }
    public PedidoC(Cliente cliente, EstadoPed estadoPed, Date fechaA, Float total, Set lineaPedidoCs) {
       this.cliente = cliente;
       this.estadoPed = estadoPed;
       this.fechaA = fechaA;
       this.total = total;
       this.lineaPedidoCs = lineaPedidoCs;
    }
   
    public Integer getIdPedidoC() {
        return this.idPedidoC;
    }
    
    public void setIdPedidoC(Integer idPedidoC) {
        this.idPedidoC = idPedidoC;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public EstadoPed getEstadoPed() {
        return this.estadoPed;
    }
    
    public void setEstadoPed(EstadoPed estadoPed) {
        this.estadoPed = estadoPed;
    }
    public Date getFechaA() {
        return this.fechaA;
    }
    
    public void setFechaA(Date fechaA) {
        this.fechaA = fechaA;
    }
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }
    public Set getLineaPedidoCs() {
        return this.lineaPedidoCs;
    }
    
    public void setLineaPedidoCs(Set lineaPedidoCs) {
        this.lineaPedidoCs = lineaPedidoCs;
    }




}


