package modelos;
// Generated 14-abr-2015 0:15:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PedidoP generated by hbm2java
 */
public class PedidoP  implements java.io.Serializable {


     private Integer numPed;
     private EstadoPed estadoPed;
     private FormaPago formaPago;
     private Proveedor proveedor;
     private Date fechaA;
     private String total;
     private String tipo;
     private Set lineaPedidoPs = new HashSet(0);

    public PedidoP() {
    }

	
    public PedidoP(EstadoPed estadoPed, FormaPago formaPago, Proveedor proveedor, Date fechaA, String tipo) {
        this.estadoPed = estadoPed;
        this.formaPago = formaPago;
        this.proveedor = proveedor;
        this.fechaA = fechaA;
        this.tipo = tipo;
    }
    public PedidoP(EstadoPed estadoPed, FormaPago formaPago, Proveedor proveedor, Date fechaA, String total, String tipo, Set lineaPedidoPs) {
       this.estadoPed = estadoPed;
       this.formaPago = formaPago;
       this.proveedor = proveedor;
       this.fechaA = fechaA;
       this.total = total;
       this.tipo = tipo;
       this.lineaPedidoPs = lineaPedidoPs;
    }
   
    public Integer getNumPed() {
        return this.numPed;
    }
    
    public void setNumPed(Integer numPed) {
        this.numPed = numPed;
    }
    public EstadoPed getEstadoPed() {
        return this.estadoPed;
    }
    
    public void setEstadoPed(EstadoPed estadoPed) {
        this.estadoPed = estadoPed;
    }
    public FormaPago getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(FormaPago formaPago) {
        this.formaPago = formaPago;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Date getFechaA() {
        return this.fechaA;
    }
    
    public void setFechaA(Date fechaA) {
        this.fechaA = fechaA;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getLineaPedidoPs() {
        return this.lineaPedidoPs;
    }
    
    public void setLineaPedidoPs(Set lineaPedidoPs) {
        this.lineaPedidoPs = lineaPedidoPs;
    }




}


