package modelos;
// Generated 14-abr-2015 0:15:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PedidoC generated by hbm2java
 */
public class PedidoC  implements java.io.Serializable {


     private Integer numPed;
     private Cliente cliente;
     private EstadoPed estadoPed;
     private FormaPago formaPago;
     private Date fechaA;
     private Float total;
     private String destino;
     private String tipo;
     private Set lineaPedidoCs = new HashSet(0);

    public PedidoC() {
    }

	
    public PedidoC(Cliente cliente, EstadoPed estadoPed, FormaPago formaPago, Date fechaA, String destino, String tipo) {
        this.cliente = cliente;
        this.estadoPed = estadoPed;
        this.formaPago = formaPago;
        this.fechaA = fechaA;
        this.destino = destino;
        this.tipo = tipo;
    }
    public PedidoC(Cliente cliente, EstadoPed estadoPed, FormaPago formaPago, Date fechaA, Float total, String destino, String tipo, Set lineaPedidoCs) {
       this.cliente = cliente;
       this.estadoPed = estadoPed;
       this.formaPago = formaPago;
       this.fechaA = fechaA;
       this.total = total;
       this.destino = destino;
       this.tipo = tipo;
       this.lineaPedidoCs = lineaPedidoCs;
    }
   
    public Integer getNumPed() {
        return this.numPed;
    }
    
    public void setNumPed(Integer numPed) {
        this.numPed = numPed;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public EstadoPed getEstadoPed() {
        return this.estadoPed;
    }
    
    public void setEstadoPed(EstadoPed estadoPed) {
        this.estadoPed = estadoPed;
    }
    public FormaPago getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(FormaPago formaPago) {
        this.formaPago = formaPago;
    }
    public Date getFechaA() {
        return this.fechaA;
    }
    
    public void setFechaA(Date fechaA) {
        this.fechaA = fechaA;
    }
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getLineaPedidoCs() {
        return this.lineaPedidoCs;
    }
    
    public void setLineaPedidoCs(Set lineaPedidoCs) {
        this.lineaPedidoCs = lineaPedidoCs;
    }




}


