package modelos;
// Generated 11-abr-2015 20:27:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PedidoP generated by hbm2java
 */
public class PedidoP  implements java.io.Serializable {


     private Integer idPedidoP;
     private EstadoPed estadoPed;
     private Proveedor proveedor;
     private Date fechaA;
     private String total;
     private Set lineaPedidoPs = new HashSet(0);

    public PedidoP() {
    }

	
    public PedidoP(EstadoPed estadoPed, Proveedor proveedor, Date fechaA) {
        this.estadoPed = estadoPed;
        this.proveedor = proveedor;
        this.fechaA = fechaA;
    }
    public PedidoP(EstadoPed estadoPed, Proveedor proveedor, Date fechaA, String total, Set lineaPedidoPs) {
       this.estadoPed = estadoPed;
       this.proveedor = proveedor;
       this.fechaA = fechaA;
       this.total = total;
       this.lineaPedidoPs = lineaPedidoPs;
    }
   
    public Integer getIdPedidoP() {
        return this.idPedidoP;
    }
    
    public void setIdPedidoP(Integer idPedidoP) {
        this.idPedidoP = idPedidoP;
    }
    public EstadoPed getEstadoPed() {
        return this.estadoPed;
    }
    
    public void setEstadoPed(EstadoPed estadoPed) {
        this.estadoPed = estadoPed;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Date getFechaA() {
        return this.fechaA;
    }
    
    public void setFechaA(Date fechaA) {
        this.fechaA = fechaA;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public Set getLineaPedidoPs() {
        return this.lineaPedidoPs;
    }
    
    public void setLineaPedidoPs(Set lineaPedidoPs) {
        this.lineaPedidoPs = lineaPedidoPs;
    }




}


