package modelos;
// Generated 14-abr-2015 21:45:23 by Hibernate Tools 4.3.1



/**
 * Tarifa generated by hbm2java
 */
public class Tarifa  implements java.io.Serializable {


     private Integer idTarifa;
     private String nombre;
     private float porcent;

    public Tarifa() {
    }

    public Tarifa(String nombre, float porcent) {
       this.nombre = nombre;
       this.porcent = porcent;
    }
   
    public Integer getIdTarifa() {
        return this.idTarifa;
    }
    
    public void setIdTarifa(Integer idTarifa) {
        this.idTarifa = idTarifa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public float getPorcent() {
        return this.porcent;
    }
    
    public void setPorcent(float porcent) {
        this.porcent = porcent;
    }




}


